### ISSUE TITLE
Sap Bar UI

### ISSUE THREAD

**Issue by NicolaeChristof** [NicolaeChristof/Rise#76]

**Comment by AadamM** [comment]
Put in 4 hours

**Comment by AadamM** [comment]
Functionality wise it's been implemented. I'm planning to add in the new sap branch art. Overall, this task has taken approximately 8 hours.

**Comment by AadamM** [comment]
This is being worked on in the enhancement_sapUINewBranches branch. It replaces the current branch art with the new pictures, as well as ensuring the branches don't appear on the main menu. Most of the branch UI code has been moved over to the UI script.

**Comment by AadamM** [comment]
Just integrated the branch provider and UIBranchElement that Malcolm made into the branch enhancement_revisedBranchUI.
